changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - 'Doc: Improvement'
    authors:
      - octocat
      - dependabot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - 'Type: Breaking Change'
    - title: Component 🧰
      labels:
        - 'Component'
        - Semver-Minor
        - 'Type: Enhancement'
    - title: Fixed 🐛
      labels:
        - 'Type: Bug'
    - title: Other Changes
      labels:
        - '*'
