changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
      - documentation
    authors:
      - octocat
      - dependabot
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Component 🧰
      labels:
        - component
        - Semver-Minor
        - enhancement
    - title: Fixed 🐛
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
