codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
  coverage:
    precision: 2
    round: down
    range: "98...100"
    status:
      project:
        default:
          enabled: yes
          target: auto
          threshold: 0.5%
      patch:
        default:
          enabled: no

