name: 'Checkout'
description: 'Checkout repository'
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        fetch-depth: 0
