name: 'E2E testing'
description: 'Setup Playwright and run E2E tests'
runs:
  using: composite
  steps:
    - name: Install
      uses: ./.github/composite-actions/install

    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      shell: bash
      run: npm run test:e2e

    - uses: actions/upload-artifact@v4
      with:
        name: e2e-report
        path: 'e2e/report/'
        retention-days: 30
