name: 'Accessibility checking (v2)'
description: 'Build and serve Storybook pages then check accessibility'
runs:
  using: composite
  steps:
    - name: Install
      uses: ./.github/composite-actions/install

    - name: Install Playwright Browsers
      shell: bash
      run: npx playwright install --with-deps

    - name: Run tests
      shell: bash
      run: npm run test:a11y

    - uses: actions/upload-artifact@v4
      with:
        name: a11y-report
        path: 'e2e/report/a11y/'
        retention-days: 30
