name: mirror
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,19 * * 1,2,3,4,5"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.GH_ENTERPRISE_INTERNAL_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.GH_ENTERPRISE_INTERNAL_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          eval "$(ssh-agent)"
      - name: Add remote internal repository url
        run: git remote add internal ${{ secrets.GH_ENTERPRISE_INTERNAL_SSH_REPOSITORY_URL }}
      - name: Push main to internal repository
        run: git push -u internal main --force