name: mirror
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7,19 * * 1,2,3,4,5"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Add SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.GH_ENTERPRISE_INTERNAL_SSH_PRIVATE_KEY }}" > ~/.ssh/github_actions
          echo "${{ secrets.GH_ENTERPRISE_INTERNAL_SSH_PUBLIC_KEY }}" > ~/.ssh/github_actions.pub
          ssh-keyscan github.mpi-internal.com >> /home/runner/.ssh/known_hosts
          chmod 600 ~/.ssh/github_actions
          chmod 600 ~/.ssh/github_actions.pub
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null	
          ssh-add /home/runner/.ssh/github_actions
          eval "$(ssh-agent)"
      - name: Add remote internal repository url
        run: git remote add internal ${{ secrets.GH_ENTERPRISE_INTERNAL_SSH_REPOSITORY_URL }}
      - name: Push main to internal repository
        run: git push -u internal main --force