name: quality
env:
  FORCE_COLOR: 3
on:
  pull_request:
    branches:
      - main
      - 'canary/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  assign-pr-owner:
    runs-on: ubuntu-latest
    name: PR assignment
    steps:
      - name: Assign PR
        uses: toshimaru/auto-author-assign@v1.6.0
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Lint
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    name: Typecheck
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Type checking
        run: npm run typecheck

  test:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Test
        run: npm run test:coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: false
          file: ./dist/coverage/.coverage.json
          token: ${{ secrets.CODECOV_TOKEN }}
          name: Codecov UI
          codecov_yml_path: ./.codecov.yml

  test-e2e:
    runs-on: ubuntu-latest
    name: E2E tests
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        uses: tj-actions/changed-files@v41
        id: e2efiles
        with:
          files: |
            ./e2e/**/*.{ts,tsx}
            ./packages/components/**/*.{ts,tsx,mdx,json}

      - name: E2E testing
        if: steps.e2efiles.outputs.all_changed_files_count > 0
        uses: ./.github/composite-actions/e2e

  a11y:
    runs-on: ubuntu-latest
    name: Accessibility
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        uses: tj-actions/changed-files@v41
        id: files
        with:
          files: ./packages/components/**/*.{ts,tsx,mdx,json}

      - name: Accessibility checking
        if: steps.files.outputs.all_changed_files_count > 0
        uses: ./.github/composite-actions/a11y

  a11y-with-playwright:
    runs-on: ubuntu-latest
    name: Playwright Accessibility
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run tests
        run: npm run test:a11y

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-a11y-report
          path: playwright-a11y-report/
          retention-days: 30

  deploy:
    runs-on: ubuntu-latest
    name: Deployment
    environment:
      name: ${{ github.event_name != 'pull_request' && 'Production' || 'Preview'}}
      url: ${{ steps.deployment.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest --no-save --no-fund --no-audit --no-scripts

      - name: Build Storybook
        run: npm run storybook:build

      - name: Build tailwind config viewer
        run: npm run tailwind-config-viewer:build

      - name: Deploy Storybook to Vercel
        id: deployment
        run: |
          DEPLOYMENT_URL=$(vercel deploy --token $VERCEL_TOKEN --yes)
          echo "::set-output name=url::$(echo $DEPLOYMENT_URL)"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{secrets.VERCEL_TOKEN}}

  security:
    name: Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Lava Action
        uses: adevinta/lava-action@v0
